[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dio      ; <--- Forces compatible memory access
board_build.f_flash = 40000000L   ; <--- Slows down internal flash write for stability
; upload_port = COM4

lib_deps =
    wemos/WEMOS SHT3x @ ^1.0.0
    tzapu/WiFiManager @ ^2.0.17
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    knolleary/PubSubClient @ ^2.8