[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dio
board_build.f_flash = 40000000L

; ── ADD THESE TWO LINES ──────────────────────────────────────
build_flags =
    -D MQTT_MAX_PACKET_SIZE=512   ; bigger buffer for HiveMQ TLS payloads

lib_deps =
    wemos/WEMOS SHT3x @ ^1.0.0
    tzapu/WiFiManager @ ^2.0.17
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    knolleary/PubSubClient @ ^2.8